# Generated by Django 3.2.6 on 2024-12-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
