# Generated by Django 3.2.6 on 2024-12-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_date_of_birth', models.DateField()),
                ('user_gender', models.CharField(max_length=10)),
                ('user_location', models.CharField(max_length=255)),
                ('user_image', models.ImageField(default='default_user_image.jpg', upload_to='user_images')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
