# Generated by Django 3.2.6 on 2024-12-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
