# Generated by Django 3.2.6 on 2024-12-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20241224_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='author_images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='book_images'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='user_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='user_images'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuser')),
            ],
        ),
    ]
