# Generated by Django 3.2.6 on 2024-12-25 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_alter_review_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cuser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='cuser',
            name='user',
            field=models.OneToOneField(
                null=True,  # Allow null values temporarily
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cuser',
                to='auth.user',
            ),
        ),


    ]
