# Generated by Django 3.2.6 on 2025-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_author_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.URLField(default='blank-profile-picture.png', max_length=500),
        ),
    ]
