# Generated by Django 3.2.6 on 2025-02-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_author_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='author_images'),
        ),
    ]
