# Generated by Django 5.1.4 on 2025-02-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_recentsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='marketing_link',
            field=models.URLField(default='https://www.rokomari.com/book', help_text='Link to purchase the book (e.g., Rokomari)', max_length=500),
        ),
    ]
