# Generated by Django 5.2 on 2025-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_readingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='defalut_book_image.jpg', upload_to='book_images'),
        ),
    ]
