# Generated by Django 5.2 on 2025-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
